### ISSUE TITLE
Alpha testing

### ISSUE THREAD

**Issue by redlor** [redlor/Minitask#29]
app in in Alpha Testing mode now, if you want to partecipate and know someone who can, send me you Gmail address to be added.

Thank you.

**Comment by redlor** [comment]
@danielblokus  and @Bradzer if you are interested to participate in Alpha testing, please give me your gmail address.

Thank you!

**Comment by Bradzer** [comment]
I'll be really glad to help @redlor 

My address is available on my profile I think
Anyway bradley.hounkpatin@gmail.com ;-)

**Comment by redlor** [comment]
@Bradzer thank you, I added you in the list of testers and sent you the link :)

**Comment by danielblokus** [comment]
@redlor daniel.blokus@gmail.com

**Comment by redlor** [comment]
Alpha testing closed, open Beta test started.
