### ISSUE TITLE
Delete confirmation dialog also in the details activity

### ISSUE THREAD

**Issue by redlor** [redlor/Minitask#5]
it would be good to have a confirmation  dialog when the delete button in the details activity is clicked.

**Comment by Bradzer** [comment]
Working on this.
Hope I'll be useful.
It's my first time ;)

**Comment by redlor** [comment]
Hi @Bradzer 

thank you for helping. I opened this issues to get help and also to give the chance to get experience to people new to Android, so your help is very welcome.
About the task, feel free to have a look to my code in the MainActivity, I implemented a confirmation dialog there already. You can start with it, but if you want to go with DialogFragment instead, feel free to. I learned many things by starting doing something I didn't know how to do in the beginning.
Let me know if you need help and many thanks!!!

**Comment by Bradzer** [comment]
Hi @redlor 

I'm still a beginner (started few months ago) in Android development and I feel so lucky to collaborate with such friendly people like you.

Thanks a lot to give me the chance to get some experience by working with you.

I won't hesitate to let you know when I need help ;)

**Comment by redlor** [comment]
I found that if I rotate when the dialog is showing it crashes the app

**Comment by redlor** [comment]
should have been fixed #25
