### ISSUE TITLE
[Code quality] Hardcoded strings

### ISSUE THREAD

**Issue by danielblokus** [redlor/Minitask#7]
We should remove hardcoded strings in some classes e.g. MainActivity ;lines: 299 - 312

branch: new_version

**Comment by redlor** [comment]
Hi @danielblokus, sorry i didn't see you opened this already and I opened a new Issue for all the hardcoded resources. I fixed the titles of the tabs so they can be translated but many dimensions, colors and some strings are still hardcoded in the files.
Thank you for spotting this!
